Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AngApp.Controllers
{
    public class AppController : Controller
    {
        // GET: App
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GridController.cs
using AngApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
//using MvcApplication1.Models;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Web.Services;
using System.Web.Configuration;
using Microsoft.VisualBasic;
using System.Collections;
using System.Diagnostics;
using static AngApp.Models.CodeDb;

namespace AngApp.Controllers
{
    public class GridController : Controller
    {
        public CodeDb db = new CodeDb();
        // GET: Grid
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Sales()
        {

            DataTable DT = new DataTable();
            DT = db.SqlDatatbl("SELECT INV_NUM,INV_DATE,LOC_CODE,LOC_NAME,CUST_NAME,NETAMT FROM CREDIT_INVOICE  order by inv_date desc");
            List<CodeDb.Sales> Smd = new List<CodeDb.Sales>();
            foreach (DataRow dr in DT.Rows)
            {
                Smd.Add(new CodeDb.Sales
                {

                    INV_NUM = Convert.ToString(dr["INV_NUM"]), // adding data from dataset row in to list<modeldata>
                    INV_DATE = Convert.ToDateTime(dr["INV_DATE"]),
                    LOC_CODE = Convert.ToString(dr["LOC_CODE"]),
                    LOC_NAME = Convert.ToString(dr["LOC_NAME"]),
                    CUST_NAME = Convert.ToString(dr["CUST_NAME"]),
                    NETAMT = Convert.ToDecimal(dr["NETAMT"])

                });

            }
            //DT = new DataTable();
            //DT = db.SqlDatatbl("select bnk_code,bnk_name from bank_type");
            //ViewData["bankDetails"] = DT;

            return View(Smd);
        }

        public ActionResult SyncSales()
        {

            DataTable DT = new DataTable();
            DT = db.SqlDatatbl("SELECT INV_NUM,INV_DATE,LOC_CODE,LOC_NAME,CUST_NAME,NETAMT FROM CREDIT_INVOICE  order by inv_date desc");
            List<CodeDb.Sales> Smd = new List<Models.CodeDb.Sales>();
            foreach (DataRow dr in DT.Rows)
            {
                Smd.Add(new CodeDb.Sales
                {

                    INV_NUM = Convert.ToString(dr["INV_NUM"]), // adding data from dataset row in to list<modeldata>
                    INV_DATE = Convert.ToDateTime(dr["INV_DATE"]),
                    LOC_CODE = Convert.ToString(dr["LOC_CODE"]),
                    LOC_NAME = Convert.ToString(dr["LOC_NAME"]),
                    CUST_NAME = Convert.ToString(dr["CUST_NAME"]),
                    NETAMT = Convert.ToDecimal(dr["NETAMT"])

                });

            }
            DT = new DataTable();
            DT = db.SqlDatatbl("select bnk_code,bnk_name from bank_type");
            ViewData["bankDetails"] = DT;

            return View(Smd);
        }

        public JsonResult dtgJson(string id = null)
        {
            string invnum = id;
            DataTable dt = new DataTable();
            dt = db.SqlDatatbl("select item_code,item_name,units,qtyperunit,item_rate,item_amt from credit_invoice_tran where inv_num='" + invnum + "'");
            // return view(dt);

            //List<CodeDb.CodeDbs> lmd = new List<CodeDb.CodeDbs>();  // creating list of model.

            //DataSet ds = new DataSet();



            //foreach (DataRow dr in dt.Rows) // loop for adding add from dataset to list<modeldata>
            //{
            //    lmd.Add(new CodeDb.CodeDbs
            //    {
            //        ACCT_CODE = Convert.ToString(dr["item_code"]), // adding data from dataset row in to list<modeldata>
            //        ACCT_DESC = Convert.ToString(dr["item_name"]),
            //        OPN_BAL = Convert.ToString(dr["units"]),
            //        CLS_BAL = Convert.ToDecimal(dr["qtyperunit"]),
            //        TOTAL_CR = Convert.ToDecimal(dr["item_rate"]),
            //        TOTAL_DR = Convert.ToDecimal(dr["item_amt"])
            //    });
            //}

            DataTable DT = new DataTable();
            DT = db.SqlDatatbl("SELECT INV_NUM,INV_DATE,LOC_CODE,LOC_NAME,CUST_NAME,NETAMT FROM CREDIT_INVOICE  order by inv_date desc");
            List<CodeDb.Sales> Smd = new List<Models.CodeDb.Sales>();
            foreach (DataRow dr in DT.Rows)
            {
                Smd.Add(new CodeDb.Sales
                {

                    INV_NUM = Convert.ToString(dr["INV_NUM"]), // adding data from dataset row in to list<modeldata>
                    INV_DATE = Convert.ToDateTime(dr["INV_DATE"]),
                    LOC_CODE = Convert.ToString(dr["LOC_CODE"]),
                    LOC_NAME = Convert.ToString(dr["LOC_NAME"]),
                    CUST_NAME = Convert.ToString(dr["CUST_NAME"]),
                    NETAMT = Convert.ToDecimal(dr["NETAMT"])

                });

            }

            DataTable ddt = new DataTable();
            ddt = db.SqlDatatbl("select inv_num,inv_date,loc_code,loc_name,cust_name,netamt from credit_invoice where inv_num='" + invnum + "'");
            string INV1 = ddt.Rows[0]["inv_num"].ToString();
            string IND = ddt.Rows[0]["inv_date"].ToString();
            ViewData["invnum"] = INV1;
            ViewData["invdate"] = IND;
            return Json(Smd, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExportToExcel(DataTable dt)
        {
            var gv = new GridView();
            gv.DataSource = dt;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return View("Index");
        }

    }
}

Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

<h2>The page you are looking for cannot be found.<br />
    Please check the URL.</h2>

Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu .dropdown-menu {
                top: 0;
                left: 100%;
                margin-top: -1px;
            }
    </style>
    <base href="/">

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@


    <!-- Polyfill(s) for older browsers -->
    <script src="../node_modules/core-js/client/shim.min.js"></script>
    <script src="../node_modules/zone.js/dist/zone.js"></script>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../Client/systemjs.config.js"></script>
    @*<link href="../Content/bootstrap.css" rel="stylesheet" />*@
    @*<link href="../Content/bootstrap-datetimepicker.css" rel="stylesheet" />*@
    <script>
        System.import('../Client/main.js').catch(function (err) { console.error(err); });
    </script>

    <script src="../Scripts/jquery-3.3.1.min.js"></script>
    <script src="../Scripts/bootstrap.min.js"></script>
    <link href="../Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />

    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@

    @*<script src="~/Scripts/jquery-3.3.1.js"></script>
        <script src="~/Scripts/moment.js"></script>
        <script src="~/Scripts/bootstrap.js"></script>*@
        @*<script src="../Scripts/bootstrap-datetimepicker.js"></script>
        <script src="../Scripts/Site.js"></script>*@

</head>
<body>


    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("My Page", "Index", "App")</li>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Asp Grig", "Sales", "Grid")</li>
                        <li>@Html.ActionLink("Sync Grid", "SyncSales", "Grid")</li>
                        <li>@Html.ActionLink("Logout", "Login", "Home")</li>
                    </ul>
                </div>
                @ *<div>Login Details</div>* @
            </div>
        </div>*@
    <div class="container">
        <div class="dropdown">
            <button class="btn btn-default" type="button" data-toggle="dropdown">
                Masters
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Country Master", "CountryMaster", "Home")</li>
                <li>@Html.ActionLink("Department Master", "DepartmentMaster", "Home")</li>
                <li>@Html.ActionLink("Employee Master Old", "Employee", "Home")</li>
                <li>@Html.ActionLink("Employee Master", "EmployeeSave", "Home")</li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-default" type="button" data-toggle="dropdown">
                Listing
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Country List", "CountryList", "Home")</li>
                <li>@Html.ActionLink("Department List", "DepartmentList", "Home")</li>
                <li>@Html.ActionLink("Employee List Old", "EmployeeList", "Home")</li>
                <li>@Html.ActionLink("Employee List", "EmpList", "Home")</li>
                <li>@Html.ActionLink("Employee List JQuery", "GetEmployeeLstJQuery", "Home")</li>
                <li>@Html.ActionLink("Multiple Data", "MulitpleData", "Home")</li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-default" type="button" data-toggle="dropdown">
                Exporting
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Employee Export", "Export_EmployeeLst", "Home")</li>
            </ul>
        </div>
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                Others
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("My Page", "Index", "App")</li>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="dropdown-submenu">
                    <a class="test" tabindex="-1" href="#">New dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">

                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li class="dropdown-submenu">
                            <a class="test" href="#">Another dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Asp Grig", "Sales", "Grid")</li>
                                <li>@Html.ActionLink("Sync Grid", "SyncSales", "Grid")</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    @*<script>
            $(document).ready(function () {
                $('.dropdown-submenu a.test').on("click", function (e) {
                    $(this).next('ul').toggle();
                    e.stopPropagation();
                    e.preventDefault();
                });
            });
        </script>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
        </html>