Controllers/TransController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AngApp.Models;
using AngApp.ViewModel;
using System.Web.Security;
using System.Data;
using System.Data.SqlClient;
using System.Linq.Dynamic;
using System.IO;
using System.Web.Optimization;
using System.Net.Http;
using System.Data.Entity;

namespace AngApp.Controllers
{
    public class TransController : Controller
    {
        OVODEntities5 db = new OVODEntities5();
        string result = "Error! Document Creation Is Not Completed.";

        // GET: Trans
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult De_PayrollAdj(string DocNo="")
        {
            List<HD_HRPAYADJ> payadjh = new List<HD_HRPAYADJ>();
            if (DocNo != "")
            {
                OVODEntities5 oe = new OVODEntities5();
                var v = (from a in oe.VW_HD_HRPAYADJ
                         where a.PA_DOCNO.Equals(DocNo)
                         orderby a.PA_DOCNO
                         select a
                         ).FirstOrDefault();
                ViewBag.DocNo = v.PA_DOCNO;
                ViewBag.DocDate =Convert.ToDateTime( v.PA_DOCDATE).ToShortDateString();
                ViewBag.Month = v.PA_MONTH;
                ViewBag.Year = v.PA_YEAR;
                ViewBag.Header = v.PA_HEADER;
                ViewBag.PATitle = v.PA_TITLE;
            }
            return View(payadjh);
        }

        public ActionResult PayadjSave(string PA_DOCNO, string PA_DOCDATE, string PA_HEADER, string PA_TITLE, string PA_MONTH, string PA_YEAR, DT_HRPAYADJ[] det)
        {
            int DocId;
            if (PA_DOCNO != null || PA_DOCDATE != null || PA_MONTH != null || PA_YEAR != null)
            {
                using (var context = new OVODEntities5())
                {
                    using (var dbcxtransaction = context.Database.BeginTransaction())
                    {
                        try
                        {
                            var DocData = context.HD_HRPAYADJ.Where(x => x.PA_DOCNO == PA_DOCNO).FirstOrDefault();
                            if (DocData != null)
                            {
                                //HD_HRPAYADJ hd = new HD_HRPAYADJ()
                                //{
                                //    PA_DOCDATE = Convert.ToDateTime(PA_DOCDATE),
                                //    PA_HEADER = PA_HEADER,
                                //    PA_TITLE = PA_TITLE,
                                //    PA_MONTH = PA_MONTH,
                                //    PA_YEAR = PA_YEAR
                                //};
                                DocData.PA_DOCDATE = Convert.ToDateTime(PA_DOCDATE);
                                DocData.PA_HEADER = PA_HEADER;
                                DocData.PA_TITLE = PA_TITLE;
                                DocData.PA_MONTH = PA_MONTH;
                                DocData.PA_YEAR = PA_YEAR; ;
                                context.Entry(DocData).State = EntityState.Modified; 
                                context.SaveChanges();
                                DocId = context.HD_HRPAYADJ.Where(x => x.PA_DOCNO == PA_DOCNO).Select(a=>a.PA_ID).Single() ;

                                //DT_HRPAYADJ details = new DT_HRPAYADJ { PAD_ID = DocId };
                                //context.Entry(details).State = EntityState.Deleted;
                                var items = context.DT_HRPAYADJ.Where(b => b.PA_ID==DocId);
                                foreach (var item in items)
                                {
                                    context.DT_HRPAYADJ.Remove(item);
                                }

                                context.SaveChanges();

                                if (DocId > 0)
                                {
                                    foreach (var item in det)
                                    {
                                        DT_HRPAYADJ s = new DT_HRPAYADJ()
                                        {
                                            PA_ID = DocId,
                                            EM_ID = item.EM_ID,
                                            TT_ID = item.TT_ID,
                                            PAD_QTY = item.PAD_QTY,
                                            PAD_RATE = item.PAD_RATE,
                                            PAD_AMT = (item.PAD_RATE * item.PAD_QTY),
                                            PAD_REMARKS = item.PAD_REMARKS

                                        };
                                        context.DT_HRPAYADJ.Add(s);
                                    }
                                    context.SaveChanges();
                                    dbcxtransaction.Commit();
                                    result = "Success! Document Update Completed.";
                                }
                                else
                                {
                                    dbcxtransaction.Rollback();
                                    result = "Invalid Code!";
                                }

                            }
                            else
                            {
                                HD_HRPAYADJ hd = new HD_HRPAYADJ()
                                {
                                    PA_DOCNO = PA_DOCNO,
                                    PA_DOCDATE = Convert.ToDateTime(PA_DOCDATE),
                                    PA_HEADER = PA_HEADER,
                                    PA_TITLE = PA_TITLE,
                                    PA_MONTH = PA_MONTH,
                                    PA_YEAR = PA_YEAR
                                };
                                context.HD_HRPAYADJ.Add(hd);
                                context.SaveChanges();
                                DocId = hd.PA_ID;

                                if (DocId > 0)
                                {
                                    foreach (var item in det)
                                    {
                                        DT_HRPAYADJ s = new DT_HRPAYADJ()
                                        {
                                            PA_ID = DocId,
                                            EM_ID = item.EM_ID,
                                            TT_ID = item.TT_ID,
                                            PAD_QTY = item.PAD_QTY,
                                            PAD_RATE = item.PAD_RATE,
                                            PAD_AMT = (item.PAD_RATE * item.PAD_QTY),
                                            PAD_REMARKS = item.PAD_REMARKS

                                        };
                                        context.DT_HRPAYADJ.Add(s);
                                    }
                                    context.SaveChanges();
                                    dbcxtransaction.Commit();
                                    result = "Success! Document Creation Completed.";
                                }
                                else
                                {
                                    dbcxtransaction.Rollback();
                                    result = "Invalid Code!";
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            result = ex.ToString();
                            dbcxtransaction.Rollback();
                        }
                    }
                }
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult PayrollAdjustmentChklst() {
            return View();
        }
              

        [HttpPost]
        public ActionResult PayrollAdjdChklst()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumndir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            int pagesize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int totalRecords = 0;

            OVODEntities5 oe = new OVODEntities5();
            var v = (from a in oe.VW_HD_HRPAYADJ
                     orderby a.PA_DOCNO
                     select a
                     );

            totalRecords = v.Count();
            var data = v.Skip(skip).Take(pagesize).ToList();
            return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult PayrollAdjdGrdDetails(string DocNo)
        {
            OVODEntities5 oe = new OVODEntities5();
            var v = (from a in oe.VW_DT_HRPAYADJ
                     where a.PA_DOCNO.Equals(DocNo)
                     orderby a.PA_DOCNO
                     select a
                     );

            return Json(v, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult LoadData()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();

Views/Trans/Leave.cshtml
@model AngApp.DT_LEAVE

@{
    ViewBag.Title = "Leave";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

@*<h2>Leave</h2>*@

@using (Html.BeginForm("Leave", "Trans", FormMethod.Post, new { id = "Leave" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @*<h4>DT_LEAVE</h4>
        <hr />*@
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <label class="control-label col-md-2">
            Doc.No. :
        </label>
        <div class="col-md-2">
            <input type="text" id="LV_DOC_NO" name="LV_DOC_NO" placeholder="Doc.No" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            Doc.Date :
        </label>
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.LV_DOC_DATE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LV_DOC_DATE, "", new { @class = "text-danger" })*@
            <input type="text" id="LV_DOC_DATE" name="LV_DOC_DATE"
                   placeholder="Doc.Date"
                   class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            Employee :
        </label>
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.LV_EMPNO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LV_EMPNO, "", new { @class = "text-danger" })*@
            <div class="col-md-2 text-left">
                <input type="text" id="EMP_ID" name="EMP_ID" placeholder="Emp.Code" class="form-control" />
            </div>
            <div class="col-md-4 text-left">
                <input type="text" id="EM_NAME" name="EM_NAME" placeholder="Emp.Name" class="form-control" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            Email :
        </label>
        <div class="col-md-10">
            @*<div class="col-md-8 text-left">*@
                <input type="text" id="LV_EMAIL" name="LV_EMAIL" placeholder="Email" class="form-control" />
            @*</div>*@
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.TT_ID, "TT_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TT_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TT_ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            TT :
        </label>
        <div class="col-md-10">
            <div class="col-md-2 text-left">
                <input type="text" id="TT_ID" name="TT_ID" placeholder="TT.Code" class="form-control" />
            </div>
            <div class="col-md-4 text-left">
                <input type="text" id="TTDesc" name="TTDesc" placeholder="TT.Desc" class="form-control" />
            </div>
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            Date From :
        </label>
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.LV_DT_FROM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LV_DT_FROM, "", new { @class = "text-danger" })*@
            <input type="text" id="LV_DT_FROM" name="LV_DT_FROM"
                   placeholder="Date From"
                   class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2 text-right">
            Date To :
        </label>
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.LV_DT_TO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LV_DT_TO, "", new { @class = "text-danger" })*@
            <input type="text" id="LV_DT_TO" name="LV_DT_TO"
                   placeholder="Date To"
                   class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        @if (ViewBag.Message != null)
        {
        <div class="error">@ViewBag.Message</div>
        }
    </div>
</div>
}




@section scripts{

    <script>
        $(document).ready(function () {
            $('input[id$=LV_DOC_DATE]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "1950:2025",
                buttonImageOnly: true
            });
        });
        $(document).ready(function () {
            $('input[id$=LV_DT_FROM]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "1950:2025",
                buttonImageOnly: true
            });
        });
        $(document).ready(function () {
            $('input[id$=LV_DT_TO]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "1950:2025",
                buttonImageOnly: true
            });
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $("#EMP_ID").autocomplete({
                source: '/AngApp/Help/GetEmployee',
                select: function (event, ui) {
                    //set tagids to save
                    $("#EMP_ID").val(ui.item.id);
                    $("#EM_NAME").val(ui.item.desc);
                    //Tags for display
                    //this.value = ui.item.id;
                    return false;
                }
            });

            $("#EM_NAME").autocomplete({
                source: '/AngApp/Help/GetEmployee',
                select: function (event, ui) {
                    //set tagids to save
                    $("#EM_NAME").val(ui.item.desc);
                    $("#EMP_ID").val(ui.item.id);
                    //Tags for display
                    //this.value = ui.item.id;
                    return false;
                }
            });

            $("#TT_ID").autocomplete({
                source: '/AngApp/Help/GetTTLve',
                select: function (event, ui) {
                    //set tagids to save
                    $("#TT_ID").val(ui.item.id);
                    $("#TTDesc").val(ui.item.desc);
                    //Tags for display
                    //this.value = ui.item.id;
                    return false;
                }
            });

            $("#TTDesc").autocomplete({
                source: '/AngApp/Help/GetTTLve',
                select: function (event, ui) {
                    //set tagids to save
                    $("#TT_ID").val(ui.item.id);
                    $("#TTDesc").val(ui.item.desc);
                    //Tags for display
                    //this.value = ui.item.desc;
                    return false;
                }
            });

        });



    </script>
    <script src="~/Scripts/Validation.js"></script>

}

Views/Trans/PayrollAdjustmentChklst.cshtml
@{
    ViewBag.Title = "Payroll Adjustment Checkklist";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

@*<link href="~/Scripts/datatables.min.css" rel="stylesheet" />*@
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<div style="width:50%;margin:0 auto;">
    <table id="tblPaAdjh">
        <thead>
            <tr>
                <th>Doc.No.</th>
                <th>Doc.Date</th>
                <th>Month</th>
                <th>Year</th>
                <th>Header</th>
                <th>Title</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts{
    @*<script src="~/Scripts/datatables.min.js"></script>*@
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $("#tblPaAdjh").DataTable({
                "processing": true,
                "serverSide": true,
                "filter": false,
                "orderMulti": false,
                "ajax": {
                    "url": "Trans/PayrollAdjdChklst",
                    "type": "POST",
                    "datatype": "Json"
                },
                "columns": [
                    {
                        "data": "PA_DOCNO", "Code": "PA_DOCNO", "autowidth": true,
                        "mRender": function (data, type, full,meta) {
                            return '<a href="/Trans/De_PayrollAdj/?DocNo=' + full.PA_DOCNO + '">' + full.PA_DOCNO  + '</a>';
                        }},
                    {
                        "data": "PA_DOCDATE", "autowidth": true, "type": 'date',
                        "render": function (value) {
                            if (value === null) return "";
                            var pattern = /Date\(([^)]+)\)/;//date format from server side
                            var results = pattern.exec(value);
                            var dt = new Date(parseFloat(results[1]));

                            return dt.getDate() + "/" + (dt.getMonth() + 1) + "/" + dt.getFullYear();
                        }, "autoWidth": true
                    },
                    { "data": "PA_MONTH", "Month": "PA_MONTH", "autowidth": true },
                    { "data": "PA_YEAR", "Year": "PA_YEAR", "autowidth": true },
                    { "data": "PA_HEADER", "Header": "PA_HEADER", "autowidth": true },
                    { "data": "PA_TITLE", "Header": "PA_TITLE", "autowidth": true },
                    {
                        data: null,
                        className: "center",
                        defaultContent: '<a href="@Url.Action("De_PayrollAdj", "Trans", new { DocNo = " + data + " })">Edit</a>'
                    }
                ]
            });
        });

       

    </script>
}