Controllers/MedicalController.cs
using AngApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AngApp.Controllers
{
    public class MedicalController : Controller
    {
        //private ILog _ILog;
        //public MedicalController()
        //{
        //    _ILog = Log.GetInstance;
        //}

        //protected override void OnException(ExceptionContext filterContext)
        //{
        //    _ILog.LogException(filterContext.Exception.ToString());
        //    filterContext.ExceptionHandled = true;
        //    this.View("Error").ExecuteResult(this.ControllerContext);
        //}

        // GET: Medical
        public ActionResult Index()
        {
            return RedirectToAction("GetDiagnosis");
        }

        public ActionResult GetDiagnosis()
        {
            OVODEntities5 _context = new OVODEntities5();
            return View(_context.DIAGNOSIS.ToList());
        }

        public ActionResult GetDiagnosisDetails(int id)
        {
            OVODEntities5 _context = new OVODEntities5();
            var model = _context.DIAGNOSIS
                .Where(x => x.ID == id)
                .FirstOrDefault();
            return View(model);
        }
             

        [HttpPost]
        public ActionResult Diagnosis(DIAGNOSI dIAGNOSI)
        {
            OVODEntities5 db = new OVODEntities5();
            var model = db.DIAGNOSIS.Where(x => x.ID.Equals(dIAGNOSI.ID)).FirstOrDefault();
            model.DIAGNOSIS = dIAGNOSI.DIAGNOSIS;
            db.SaveChanges();
            return RedirectToAction("GetDiagnosis");
        }

        public ActionResult GetDrug(int? id)
        {
            //throw new Exception("Something went wrong");
            OVODEntities5 _context = new OVODEntities5();
            var model = _context.DRUGs.ToList();
            if (id != null)
            {
                model = _context.DRUGs
                       .Where(x => x.DIG_ID == id)
                       .ToList();
            }
            return View(model);
        }

        public ActionResult DrugDetails(DRUG dRUG)
        {
            OVODEntities5 _context = new OVODEntities5();
            var model = _context.DRUGs
                .Where(x => x.ID == dRUG.ID)
                .FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        public ActionResult Drugs(DRUG dRUG)
        {
            OVODEntities5 db = new OVODEntities5();
            var model = db.DRUGs
                .Where(x => x.ID.Equals(dRUG.ID)).ToList();
            DRUG di = new DRUG()
            {
                DRUG1 = dRUG.DRUG1
            };
            di.ID.Equals(dRUG.ID);
            db.SaveChanges();
            return RedirectToAction("GetDrug");
        }
    }
}

Views/Medical/DrugDetails.cshtml
@model AngApp.DRUG

@{
    ViewBag.Title = "Drug Details";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}


@*<h2>Drug Details</h2>*@

@using (Html.BeginForm("Diagnosis", "Medical"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>DRUG</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DRUG1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DRUG1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DRUG1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Medical/GetDiagnosis.cshtml
@model IEnumerable<AngApp.DIAGNOSI>

@{
    ViewBag.Title = "Diagnosis";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

@*<h2>Diagnosis</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CODE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DIAGNOSIS)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CODE)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.DIAGNOSIS)*@
            @Html.ActionLink(item.DIAGNOSIS, "GetDrug", new { id = item.ID })
        </td>
        <td>
            @Html.ActionLink("Edit", "GetDiagnosisDetails", new { id=item.ID }) 
            @*|
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}

</table>

Views/Medical/GetDiagnosisDetails.cshtml
@model AngApp.DIAGNOSI

@{
    ViewBag.Title = "Diagnosis Details";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

@*<h2>Diagnosis Details</h2>*@

@using (Html.BeginForm("Diagnosis","Medical"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>DIAGNOSI</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIAGNOSIS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIAGNOSIS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIAGNOSIS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Medical/GetDrug.cshtml
@model IEnumerable<AngApp.DRUG>

@{
    ViewBag.Title = "Drug";
    Layout = "~/Views/Shared/SubTheme.cshtml";
}

@*<h2>Drug</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CODE)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.DRUG1)*@
            <text>DRUG</text>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CODE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DRUG1)
        </td>
        <td>
            @Html.ActionLink("Edit", "DrugDetails", new { id=item.ID }) 
            @*|
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })*@
        </td>
    </tr>
}

</table>